# Copyright IBM Corp. 2013, 2025
# SPDX-License-Identifier: MPL-2.0

version: 2
project_name: packer-plugin-sdk
builds:
  -
    skip: true
release:
  ids:
    - 'none'
changelog:
  use: github-native
