go list -m -u github.com/hashicorp/packer-plugin-sdk
go list -m -u github.com/agext/levenshtein
go list -m -u github.com/aws/aws-sdk-go
go list -m -u github.com/dylanmei/winrmtest
go list -m -u github.com/fatih/camelcase
go list -m -u github.com/fatih/structtag
go list -m -u github.com/gofrs/flock
go list -m -u github.com/google/go-cmp
go list -m -u github.com/google/shlex
go list -m -u github.com/google/uuid
go list -m -u github.com/hashicorp/consul/api
go list -m -u github.com/hashicorp/go-getter/gcs/v2
go list -m -u github.com/hashicorp/go-getter/s3/v2
go list -m -u github.com/hashicorp/go-getter/v2
go list -m -u github.com/hashicorp/go-multierror
go list -m -u github.com/hashicorp/go-version
go list -m -u github.com/hashicorp/hcl/v2
go list -m -u github.com/hashicorp/vault/api
go list -m -u github.com/hashicorp/yamux
go list -m -u github.com/jehiah/go-strftime
go list -m -u github.com/masterzen/winrm
go list -m -u github.com/mitchellh/cli
go list -m -u github.com/mitchellh/go-fs
go list -m -u github.com/mitchellh/iochan
go list -m -u github.com/mitchellh/mapstructure
go list -m -u github.com/mitchellh/reflectwalk
go list -m -u github.com/packer-community/winrmcp
go list -m -u github.com/pkg/diff
go list -m -u github.com/pkg/errors
go list -m -u github.com/pkg/sftp
go list -m -u github.com/ryanuber/go-glob
go list -m -u github.com/stretchr/testify
go list -m -u github.com/ugorji/go/codec
go list -m -u github.com/zclconf/go-cty
go list -m -u golang.org/x/crypto
go list -m -u golang.org/x/mobile
go list -m -u golang.org/x/mod
go list -m -u golang.org/x/net
go list -m -u golang.org/x/sync
go list -m -u golang.org/x/term
go list -m -u golang.org/x/tools
